### ISSUE TITLE
Cleanup JAVA paths in utils and others

### ISSUE THREAD

**Issue by rbertran** [IBM/eraser#10]
Remove spurious path from `utils/vcdstats` files, and implement a more robust java path detection.

- [x] Remove spurious paths
- [x] Robust current directory detection (not rely on `$BASH_SOURCE[0]` variable)
- [x] Java availability should be check in `eraser_setenv` 
- [x] Dependencies (e.g. bash?, java? etc...) should be documentes

**Comment by karthiksv** [comment]
Added a dependency checker which runs automatically in eraser_setenv
